# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(615, 291)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 581, 191))
        self.groupBox.setObjectName("groupBox")
        self.SelectFile = QtWidgets.QPushButton(parent=self.groupBox)
        self.SelectFile.setGeometry(QtCore.QRect(220, 70, 101, 24))
        self.SelectFile.setObjectName("SelectFile")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.SelectedFile = QtWidgets.QLabel(parent=self.groupBox)
        self.SelectedFile.setGeometry(QtCore.QRect(100, 20, 471, 41))
        self.SelectedFile.setObjectName("SelectedFile")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 191, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 191, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 191, 16))
        self.label_4.setObjectName("label_4")
        self.items_lv_0 = QtWidgets.QLabel(parent=self.groupBox)
        self.items_lv_0.setGeometry(QtCore.QRect(220, 100, 49, 16))
        self.items_lv_0.setObjectName("items_lv_0")
        self.items_lv_1 = QtWidgets.QLabel(parent=self.groupBox)
        self.items_lv_1.setGeometry(QtCore.QRect(220, 120, 200, 16))
        self.items_lv_1.setObjectName("items_lv_1")
        self.items_lv_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.items_lv_2.setGeometry(QtCore.QRect(220, 140, 49, 16))
        self.items_lv_2.setObjectName("items_lv_2")
        self.ConvertFile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ConvertFile.setGeometry(QtCore.QRect(240, 240, 101, 24))
        self.ConvertFile.setObjectName("ConvertFile")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 210, 351, 16))
        self.label_5.setObjectName("label_5")
        self.max_items_lv0 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.max_items_lv0.setGeometry(QtCore.QRect(420, 210, 113, 22))
        self.max_items_lv0.setObjectName("max_items_lv0")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Данные исходного файла"))
        self.SelectFile.setText(_translate("MainWindow", "Выбрать файл"))
        self.label.setText(_translate("MainWindow", "Путь к файлу:"))
        self.SelectedFile.setText(_translate("MainWindow", "Имя файла"))
        self.label_2.setText(_translate("MainWindow", "Едениц level0 (условные изделия):"))
        self.label_3.setText(_translate("MainWindow", "Едениц level1 (условные коробки):"))
        self.label_4.setText(_translate("MainWindow", "Едениц level2 (условные палеты):"))
        self.items_lv_0.setText(_translate("MainWindow", "-"))
        self.items_lv_1.setText(_translate("MainWindow", "-"))
        self.items_lv_2.setText(_translate("MainWindow", "-"))
        self.ConvertFile.setText(_translate("MainWindow", "Конвертировать"))
        self.label_5.setText(_translate("MainWindow", "Ограничение на формирование файла по количеству в level0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
